
{{ if .Values.argocd.giropopsSenhas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  destination:
    namespace: giropops-senhas
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: "giropopsSenhas.replicas"
        value: "{{ .Values.argocd.giropopsSenhas.replicas }}"
      valueFiles:
      - app-of-apps/values.yaml
    path: giropops-senhas/helm
    repoURL: https://github.com/DiogoMajela/descomplicando-gitops-no-kubernetes-argocd.git
    targetRevision: feat/day-2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  syncOptions:
  - CreateNamespace=true 
  - PruneLast=true
{{ end }}
