#{{- if .Values.argocd.giropopsSenhas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: giropops-senhas
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx/helm
    repoURL: 'https://github.com/DiogoMajela/descomplicando-gitops-no-kubernetes-argocd.git'
    targetRevision: feat/day-2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true 
    - PruneLast=true
#{{- end }}


