apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DiogoMajela/descomplicando-gitops-no-kubernetes-argocd.git'
    targetRevision: feat/day-2
    path: nginx/helm/
  destination:
    server: https://kubernetes.default.svc
    namespace: giropops-senhas
  syncPolicy:
    automated:  
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    
